### ISSUE TITLE
Discussion about OpenCL possibilities

### ISSUE THREAD

**Issue by unbornchikken** [unbornchikken/NOOOCL#3]
Hi @metabench,

We've talked about the **fast** OpenCL average calculation. This is not so easy, it's even cannot be achieved on the current devices. Doable but not fast.

First you a need a reduction on each core:  http://developer.amd.com/resources/documentation-articles/articles-whitepapers/opencl-optimization-case-study-simple-reductions/ calculating the sum. Then comes the slow part, you have to do global atomics to sum up the result from the cores. Counting the host - device data copy and the kernel launching overhead on top of this, I don't think that this can beat a well optimized CPU based average calculation code.

**Comment by metabench** [comment]
Thanks for that link. I don't yet understand some things about the code there, it's introduced some new concepts such as `barrier(CLK_LOCAL_MEM_FENCE);`.

The code I've just written for the averages calculation is at https://github.com/metabench/opencljs-experiments/blob/master/average.js

Anyway, I've made some progress in calculating averages, I'm taking a reduce-based approach as well.

My guess is if there is considerable overhead in sending and receiving the data then the overhead may be more than using SIMD instructions on the CPU to calculate averages. When the data is on the GPU anyway, it's probably a different matter.

Also, even if the CPU is fast at calculating averages, it may be better in some cases to use the CPU for more complicated tasks. Anyway, I'll have more results about doing the calculations on the GPU before long.

**Comment by unbornchikken** [comment]
Just seeing experimental code of yours, I've came up with two suggestions:

- In Node.js you should avoid synchronous OpenCL invocations altogether. If you do buffer reads in synchronous manner, then till the whole queue completed and data copied back to host it blocks the main node thread. Because node is single threaded, it will block the whole system. For example if you're making a node-webkit/nw.js/atomshell application, the UI will hang up till the computation and the copying gets done.
- I've noticed that you have the misconception about GPGPU programming that the every newcomer has (I had that too): you think that anything goes on the GPU it must be as fast as hell. That is not the case. Most operations are slower to execute on the GPU than the CPU. GPU can do many unrelated computations in parallel really fast. That's it. The keywords here is parallel and unrelated. As soon as invidual computation results have to be merged somehow it will be more and more inefficient. So I suggest that you should make an imperative JS version for each of your OCL experiment code, and compare performances of those to each other by using small then a large datasets. You will be surprised.

**Comment by metabench** [comment]
I'm aware that with these small calculations it's not going to be going faster. I'm using small calculations so I can understand what it's doing.

**Comment by metabench** [comment]
I'd like to use asynchronous calls with the JavaScript, but I'm uncertain how to do it. I think I'd use libuv. It's something I'd like to be available to carry out OpenCL processes.

**Comment by unbornchikken** [comment]
Then try to use NOOOCL. I've already made that available. :) Or if you wanna do it with C++ by yourself, then look for how it was achieved in [node-opencl](https://github.com/mikeseven/node-opencl) module.

**Comment by metabench** [comment]
I'll be looking at both in detail. I'll also look at some simpler asynchronous examples.

**Comment by unbornchikken** [comment]
There is a really simple case in the ffi module on that NOOOCL relies: https://github.com/node-ffi/node-ffi/blob/master/src/callback_info.cc#L167

When a callback arises in a thread, it gets enqueued. Then main node thread gets awakened by libuv, doing a native callback that process work items in the queue.

**Comment by metabench** [comment]
Calculating averages is definitely proving a challenge. I've explored various ways of doing it. It becomes more complicated when the data set size is not a multiple of the `reduction_factor`. I've added some weighting to allow for that, but of course that would slow it down.

Also, to calculate the mean it may be easiest to calculate the total, then divide that by the number of items, rather than working out intermediate averages.

With large enough sets of data (including large enough numbers), while averaging I'm hitting the precision limit of the `double` type. This could be mitigated by lowing the `reduction_factor`, and I'll be trying this.

**Comment by metabench** [comment]
Also, it's not taking all that much to crash my graphics card, such as trying to average 800000 values.

**Comment by metabench** [comment]
Adding `release_all` to do the OpenCL releasing of memory has made it crash less frequently, but it still seems like it's filling up the memory so that it eventually fails.

**Comment by metabench** [comment]
The crashing was solved to switching my display to the integrated Haswell graphics. Now I'm able to run big OpenCL calculations without it crashing :)

While I could do more on calculating the averages with averaging throughout the process, for the moment I'm happy to calculate the total in order to get the average.

With the reduce function, I'm having it keep track of how many input elements went into each of the results. While I was planning on this being used to calculate weightings in averages (in cases that don't neatly fit into the reduction factor), I found it helpful in verifying that all the calculations had been done. I encountered problems with it not completing the calculations, but now I've corrected the code it does complete the calculations.

I'm hitting the limit of what `smalloc` will allocate. I don't know if this average calculation would be faster than SIMD or not, but so far the results are very encouraging for being able to do a lot of calculation quickly on the GPU with OpenCL.

**Comment by unbornchikken** [comment]
Maybe you could put there a link to your experiment's result that I can take a look at.

**Comment by metabench** [comment]
The code itself is at https://github.com/metabench/opencljs-experiments/blob/master/average.js. To run it you would need an each function, which it gets from jsgui (https://github.com/metabench/jsgui/blob/master/js/core/jsgui-lang-essentials.js)

The output is:
```
initializing data
JavaScript init data time:  [ 0, 939386439 ]
Done some OpenCL init.
stage_reduced_size 15000000
n_stage 0
stage_reduced_size 1875000
n_stage 1
stage_reduced_size 234375
n_stage 2
stage_reduced_size 29297
n_stage 3
stage_reduced_size 3663
n_stage 4
stage_reduced_size 458
n_stage 5
stage_reduced_size 58
n_stage 6
stage_reduced_size 8
n_stage 7
stage_reduced_size 1
n_stage 8
n_stage 8
time_diff [ 0, 22272505 ]
last_res_buffer[0] 1199974912
last_input_count_buffers[0] 120000000
```

**Comment by unbornchikken** [comment]
I did not get tiem to look at this, just I have a small suggestion: instead of each use [lodash](https://lodash.com/) which is kinda standard in JavaScript functional programming.

**Comment by metabench** [comment]
I'll stick with `jsgui-lang-essentials`. I'm making a Class in the project, and while such capabilities are within ES6, I'd need to use `--harmony` or `--harmony_classes` as a startup option. The reason that these are made into startup options I've read is to discourage their use, so I've been discouraged quickly reverted to using jsgui for classes, so it makes sense to also stick with the each loop from jsgui as well.

**Comment by unbornchikken** [comment]
By the way arrays in node has [forEach method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach), but with io.js you have [for of loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of). For of is much better because you can use yield in the loop body. Yeah, the World could be much better place if we can use classes of ES6 without harmony, but I think [mootols](http://davidwalsh.name/mootools-nodejs)' classes are good until we get them.

**Comment by metabench** [comment]
I'm not that interested in using these features that come with warnings and say they won't work on different browsers. The parts which can be very compatible between browsers I'd prefer remain to be so.

Maybe Babel would be worth using but it's a stage in the build process which I otherwise don't need. In fact, I like to be able to just run the code without building. I can't do that on the client side because I'm using browserify rather than AMD (Asynchronous Module Definition), I think that was a big improvement, but I don't want to have a build process for the server side code right now.

Maybe I'll see some examples that will get me interested in the yield method, and show how I can use it effectively.

`for...of` looks like it may save the overhead of a function call, so it may be a useful thing for efficiency while still expressing the concept neatly.

**Comment by unbornchikken** [comment]
My ES6 example uses yield.
