### ISSUE TITLE
process.exit() with active queue turn Node into unkillable zombie with 100% cpu consumption

### ISSUE THREAD

**Issue by vird** [unbornchikken/NOOOCL#8]
Sometimes launch kernel causes promise never fired. (condition is seeking)
I use nooocl with express. 

    app.get('/exit', function(req, res) {
      res.end('ok');
      process.exit();
    });

This causes a problem node process with express is finished, but other process remains zombie with PPID 1 (init process, so you can't kill it)

**Comment by unbornchikken** [comment]
Yeah, but I cannot imagine anything that might prevent this happen. There is a way to do some minor cleanup, but that gotta be synchronous: http://stackoverflow.com/questions/14031763/doing-a-cleanup-action-just-before-node-js-exits

The only viable way to prevent this could be implemented in yer application's domain. Instead of call process.exit, do a cleanup, wait for the queue, then call process.exit.
